apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
    max:
      cpu: "1"
      memory: "550Mi"
    maxLimitRequestRatio:
      memory: 2
      cpu: 1.3
