
apiVersion: v1
kind: List
metadata:
items: 
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: stress
    name: stress
  spec:
    selector:
      matchLabels:
        app: stress
    replicas: 1
    revisionHistoryLimit: 3
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: stress
      spec:
        containers:
        - env:
          - name: ARGS
            value: "--vm-bytes 128M"
          image: theog75/stress
          imagePullPolicy: Always
          name: stress
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    